apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-admin
  namespace: prod
subjects:
- kind: User
  name: prod_admin 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole 
  name: admin 
  apiGroup: rbac.authorization.k8s.io