apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-namespace-admin
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin 
  apiGroup: ""
roleRef:
  kind: ClusterRole 
  name: admin 
  apiGroup: rbac.authorization.k8s.io